SELECT
    S_INFO_WINDCODE,
    TRADE_DT,
    CRNCY_CODE,
    S_DQ_PRECLOSE,
    S_DQ_OPEN,
    S_DQ_HIGH,
    S_DQ_LOW,
    S_DQ_CLOSE,
    S_DQ_VOLUME,
    S_DQ_ADJFACTOR,
    S_DQ_PRECLOSE_WIND,
FROM
    USSTOCKEODPRICES
WHERE
    AND TRADE_DT BETWEEN 2 AND 2
ORDER BY
    TRADE_DT DESC,
    S_DQ_VOLUME DESC